version: '3.8'

services:
  redis:
    # https://hub.docker.com/_/redis
    # https://hub.docker.com/_/redis/tags?page=1&name=7.&ordering=last_updated
    image: redis:8.6.1@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
    restart: always
    container_name: redis-container
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
volumes:
  redis-data:
